### ISSUE TITLE
keyhac build手順

### ISSUE THREAD

**Issue by ghost** [crftwr/keyhac#1]
水平ホイールのご対応ありがとうございます。

ソースからbuildしたいのですが手順がわかりません

cx_Freezeとpython3.3はインストール済みです。

build時のフォルダ構成は

/tmp/ckit
※ckit-masterをリネームし配置

/tmp/keyhac
※keyhac-masterをリネームし配置
# パターン1

build時のコマンドは

> cd tmp/keyhac/
> python makefile.py build

実行後はエラーが表示されビルドされません
## エラー内容

E:\doc\tmp\a\keyhac>python makefile.py build
Traceback (most recent call last):
  File "makefile.py", line 139, in <module
    eval( target + "()" )
  File "<string>", line 1, in <module>
## NameError: name 'build' is not defined
# 
# パターン2

事前に/tmp/keyhac/docを作成

build時のコマンドは

> cd tmp/keyhac/
> python setup.py build

tmp/keyhac/dist/keyhac/keyhac.exe
が作成作成されます
keyhac.exeを実行すると

エラーが表示され
## エラー内容

---
## cx_Freeze: Python error in main script

Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\cx_Freeze\initscripts\Console3.py", line 27, in <module>
    exec(code, m.**dict**)

  File "keyhac_main.py", line 15, in <module>
  File "C:\Python\64-bit\3.3\lib\importlib_bootstrap.py", line 1567, in _find_and_load
  File "C:\Python\64-bit\3.3\lib\importlib_bootstrap.py", line 1534, in _find_and_load_unlocked

  File "..\ckit__init__.py", line 3, in <module>
  File "C:\Python\64-bit\3.3\lib\importlib_bootstrap.py", line 1567, in _find_and_load
  File "C:\Python\64-bit\3.3\lib\importlib_bootstrap.py", line 1534, in _find_and_load_unlocked

  File "ExtensionLoader_ckit_ckitcore.py", line 22, in <module>
  File "ExtensionLoader_ckit_ckitcore.py", line 14, in **bootstrap**
## ImportError: DLL load failed: %1 は有効な Win32 アプリケーションではありません。

C:\Python\64-bit....などのディレクトリは無く

pythoは
C:\Python33\にあります
# 64bitマシンなのが原因なのでしょうか?

以前質問した際パターン1が良い手順との事でしたが、、、
パターン1はエラーの原因が全くわかりません、、、

お忙しい中申し訳ありませんがよろしければアドバイスよろしくお願いします。

**Comment by crftwr** [comment]
パターン1に関してですが、

python makefile.py
または、
python makefile.py all
のように、実行してみていただけますか？

ただ、ドキュメントの生成のために、Doxygenなどいくつか追加の
ソフトウェアをインストールする必要があります。

**Comment by crftwr** [comment]
パターン2に関してですが、インストールされているPythonが、64bit版だったりするでしょうか？

ckit にバイナリで check in されている ckitcore.pyd は、32bit 用にビルドされているので、
32bit 用のPython をインストールしてみていただけますか？
(PCが64bitマシンであるとしても、です。)

**Comment by ghost** [comment]
パターン2に関して
32bitをインストール後いビルドをしてみましたが
Pillow でエラーがでます
Pillow インストールしてビルドしていみたのですができませんでした、、、

可能であればビルド済1.62版を公式サイトにてDL可能にしていただけないでしょうか、、、

**Comment by crftwr** [comment]
はい、週末になると思いますが、アップデートしますね。

**Comment by ghost** [comment]
色々とありがとうございました

**Comment by crftwr** [comment]
遅くなりましたが、1.62を公開しました。
closeします。
